/*
  Shared constants for Office Aquarium.

  Codex/reviewer rule:
  If a value represents a reusable game rule, label, timing, status, threshold,
  or default, use the constant from this file. If the needed constant does not
  exist yet, add it here first, then update every caller that depends on the
  same meaning. Do not copy/paste magic numbers or status strings across the
  simulation.
*/
function deepFreezeConstants(value){
  if(!value||typeof value!=="object"||Object.isFrozen(value))return value;
  Object.getOwnPropertyNames(value).forEach(key=>deepFreezeConstants(value[key]));
  return Object.freeze(value);
}

globalThis.OFFICE_AQUARIUM_CONSTANTS=deepFreezeConstants({
  storage:{
    saveKey:"office-aquarium-living-office-v3",
    saveVersion:40,
    transientCompanyKeys:[
      "runtime",
      "socialMemoryDebug",
      "socialConflictDebug",
      "socialLeadershipDebug",
      "lastSocialSystemsAudit"
    ],
    maxPersistedCharacters:4700000,
    compactFormat:"office-aquarium-compact-v1",
    // Append new keys only. Reordering this list would invalidate existing compact saves.
    compactKeys:[
      "saveVersion","savedAt","company","employees","ownerSystem","id","type","category",
      "day","minute","absoluteMinute","timestamp","createdDay","startedDay","completedDay",
      "lastDay","reviewedDay","lastUpdatedDay","employeeId","employeeIds","ownerId","subjectId",
      "actorId","participantIds","relatedEmployeeIds","sourceEventId","sourceId","projectId",
      "workItemId","messageId","decisionId","department","role","status","confidence","intensity",
      "context","outcome","action","strategy","title","name","tone","privacy","roomId","reasonCode",
      "stressDelta","moraleDelta","emotionalTone","sourceEvidenceIds","memberIds","employeeAId",
      "employeeBId","familiarity","interactionCount","firstMetAt","lastInteractionAt","lastSeenAt",
      "coPresenceMinutes","positiveExperienceCount","neutralExperienceCount","negativeExperienceCount",
      "recentExperiences","experienceSummary","interpretation","relationshipInputs",
      "lastRelationshipEvaluationAt","recentInteractionTypes","reputationObservations","cooldowns",
      "stressHistory","moraleHistory","count","positive","negative","neutral","mixed","lastAt",
      "records","summaries","compressedCount","emotionalRecallCooldowns","history","templateUsage",
      "recentCategoryHistory","knowledge","lastConversationByPair","exchanges","facts","contexts",
      "startedAt","visibleUntilAbsoluteMinute","speakerId","listenerId","templateId","text",
      "dimensions","evidence","value","trend","evidenceTypes","active","offsite","skills",
      "performance","learning","personality","emotionalState","memories","beliefs","goals",
      "communication","baseline","expectedChannels","attributionSources","observations",
      "contradictions","resolution","hypotheses","reviewSchedule","employeeReactions","dedupeKey",
      "relationshipBefore","relationshipAfter","projectTitle","workTitle","deadlineDay","purpose",
      "description","recommendation","risks","benefits","choices","decision","read","deleted",
      "eventId","priority","from","date","message","structuredMessage","laterOutcome","progress",
      "quality","risk","cash","board","trust","morale","stress","customers","dailyRevenue",
      "valuation","phase","randomState","nextRuntimeId",
      "pairHistory","recentTopics","recentTemplateIds","recentPartnersByEmployee",
      "triggerType","triggerEvidenceId","phaseStartedAt","exchangeSchedule",
      "startOffsetMinutes","durationMinutes","pauseAfterMinutes","endAtAbsoluteMinute",
      "conversationStartAt","resumeAt","completedAt","presence","previousPositions",
      "motion","fromX","fromY","targetX","targetY","flowCue","gesture","intent","voiceStyle",
      "durationMs","easing","pendingPosition","cue","partnerId","facing","currentExchangeIndex",
      "topicKey","memoryReferences","targets","presentationOnly","exchangeIndex",
      "schemaVersion","lastConversationAt","recentCategories","zone","currentRoom","homeRoom",
      "homeZone","x","y","actionMinutes","thought","valuationRiskScore",
      "lastAutomaticRepairCheckAt","mentorConversationRecorded"
    ]
  },
  determinism:{
    defaultRandomState:2463534242,
    firstRuntimeId:1
  },
  time:{
    minutesPerDay:1440,
    daysPerWeek:7,
    daysPerMonth:30,
    daysPerQuarter:91,
    daysPerYear:365,
    weeksPerYear:52,
    workdayStartMinute:480,
    workdayEndMinute:1200,
    offsiteReturnCutoffMinute:1020,
    unknownFutureDay:999
  },
  defaults:{
    neutralScore:50,
    healthyScore:55,
    unknownSkill:35,
    unknownLeadershipSkill:45,
    unknownSupplyRisk:35,
    unknownQualityRisk:35,
    unknownTeamCohesion:55,
    maxScore:100,
    minScore:0
  },
  departments:{
    company:"company",
    hardware:"hardware",
    software:"software",
    quality:"quality",
    product:"product",
    finance:"finance",
    people:"people",
    operations:"operations",
    customerSuccess:"customerSuccess",
    support:"support",
    core:["hardware","software","quality","product","finance","people"],
    learning:["hardware","software","quality","product","finance","people","company"],
    labor:["hardware","software","quality","product","finance","people","operations","customerSuccess","support"]
  },
  productPhases:{
    prototype:"prototype",
    integration:"integration",
    customerTrial:"customer trial",
    pilot:"pilot",
    launched:"launched",
    order:["prototype","integration","customer trial","pilot","launched"],
    commercial:["customer trial","pilot","launched"]
  },
  social:{
    modelVersion:4,
    schemaVersion:1,
    organizationViews:["culture","groups","network","leadership"],
    defaultOrganizationView:"culture",
    neutralInterpretation:{
      trust:50,
      respect:50,
      comfort:50,
      professionalFriction:0,
      confidence:0
    },
    relationshipBands:{
      substantialTrust:58,
      trusted:68,
      respected:65,
      comfortable:62,
      materialFriction:20,
      severeFriction:65
    },
    experienceTypes:[
      "shared_work_activity","shared_meeting","shared_break","conversation","direct_help",
      "help_request","blocker_resolved_together","deadline_pressure_together",
      "milestone_success_together","milestone_failure_together","recognition_shared",
      "interruption_shared","conflict_observed","crisis_response_together",
      "onboarding_support","mentoring_interaction","task_completed","department_return",
      "shared_success","successful_collaboration","constructive_feedback","recognition",
      "successful_repair","apology","apology_accepted","clarification","constructive_follow_up","same_meeting","same_break",
      "casual_conversation","routine_collaboration","professional_disagreement",
      "interrupted","ignored_request","credit_dispute","deadline_blame",
      "failed_collaboration","dismissive_comment","meeting_conflict"
    ],
    experienceAliases:{
      shared_work_event:"shared_work_activity",
      first_meeting:"conversation",
      onboarding_introduction:"onboarding_support",
      successful_help:"direct_help",
      shared_milestone:"shared_success",
      repaired_conflict:"successful_repair",
      task_finished:"task_completed",
      returned_from_department:"department_return"
    },
    passiveLegacyExperienceTypes:["same_room_presence","room_presence","co_presence"],
    positiveExperienceTypes:[
      "direct_help","shared_success","successful_collaboration","constructive_feedback",
      "recognition","recognition_shared","successful_repair","apology_accepted",
      "blocker_resolved_together","milestone_success_together","onboarding_support",
      "mentoring_interaction","task_completed"
    ],
    neutralExperienceTypes:[
      "shared_work_activity","shared_meeting","shared_break","conversation","same_meeting",
      "same_break","casual_conversation","routine_collaboration","help_request",
      "deadline_pressure_together","crisis_response_together","apology",
      "clarification","constructive_follow_up","department_return"
    ],
    negativeExperienceTypes:[
      "professional_disagreement","interrupted","ignored_request","credit_dispute",
      "deadline_blame","failed_collaboration","dismissive_comment","meeting_conflict",
      "interruption_shared","conflict_observed","milestone_failure_together"
    ],
    conflictExperienceTypes:[
      "professional_disagreement","interrupted","ignored_request","credit_dispute",
      "deadline_blame","failed_collaboration","dismissive_comment","meeting_conflict",
      "interruption_shared","conflict_observed"
    ],
    trustDamagingConflictExperienceTypes:[
      "ignored_request","credit_dispute","deadline_blame","failed_collaboration",
      "dismissive_comment"
    ],
    repairExperienceTypes:[
      "constructive_feedback","successful_repair","apology","apology_accepted",
      "clarification","constructive_follow_up","recognition",
      "direct_help","blocker_resolved_together","successful_collaboration"
    ],
    maxRecentExperiences:8,
    maxRecentInteractionTypes:8,
    maxRelationshipCooldowns:16,
    relationshipCooldownRetentionMinutes:360,
    detailedRelationshipsPerEmployee:6,
    minimumDetailedRelationships:24,
    maxSocialMemories:120,
    maxPreferenceHistory:80,
    maxPreferenceDebugEntries:24,
    maxEmotionTraces:80,
    maxReputationObservations:8,
    maxReputationChanges:12,
    familiarityKnownThreshold:15,
    passiveBreakThresholdMinutes:20,
    passiveRoomThresholdMinutes:60,
    passiveBreakFamiliarityGain:.8,
    passiveRoomFamiliarityGain:.35,
    socialNeedThreshold:55,
    projectExperience:{
      cooldownDays:7,
      pressureScheduleVariance:18,
      severeScheduleVariance:35,
      pressureRisk:68,
      severeRisk:84,
      pressureCoverage:72,
      severeCoverage:55,
      pressureOverload:12,
      severeWorkItemOverdueDays:10,
      qualityFailureIntensity:2,
      collaborationDeadlineLeadDays:7,
      collaborationTeamPressure:68
    },
    minFamiliarity:0,
    maxFamiliarity:100,
    conflict:{
      schemaVersion:1,
      maxActiveRecords:120,
      maxDebugRecords:160,
      duplicateCooldownMinutes:60,
      ignoredRequestCooldownMinutes:1440,
      minimumRepairAgeMinutes:60,
      automaticRepair:{
        ageMinutes:240,
        checkMinutes:120,
        initialThreshold:68,
        thresholdDecayPerWindow:4,
        minimumThreshold:38,
        baseReadiness:52,
        forgivenessWeight:18,
        empathyWeight:14,
        trustWeight:.1,
        psychologicalSafetyWeight:.08,
        intensityPenalty:3,
        previousAttemptPenalty:7
      },
      repairAcceptanceThreshold:48,
      frustrationHomeostasisRate:.018,
      conflictFatigueHomeostasisRate:.012
    },
    memory:{
      schemaVersion:1,
      types:[
        "helped_with_blocker","shared_success","reliable_collaboration","constructive_feedback",
        "fair_recognition","apology_received","conflict_repaired","supportive_conversation",
        "interruption","ignored_request","failed_commitment","dismissive_response","unfair_credit",
        "unresolved_disagreement","repeated_friction","unreliable_collaboration",
        "routine_meeting","routine_collaboration","casual_conversation","first_interaction",
        "mixed_outcome","stale_contact"
      ],
      typeByExperience:{
        first_met:"first_interaction",
        direct_help:"helped_with_blocker",
        blocker_resolved_together:"helped_with_blocker",
        help_request:"supportive_conversation",
        shared_success:"shared_success",
        milestone_success_together:"shared_success",
        task_completed:"shared_success",
        successful_collaboration:"reliable_collaboration",
        routine_collaboration:"routine_collaboration",
        shared_work_activity:"routine_collaboration",
        constructive_feedback:"constructive_feedback",
        mentoring_interaction:"constructive_feedback",
        recognition:"fair_recognition",
        recognition_shared:"fair_recognition",
        apology:"apology_received",
        apology_accepted:"apology_received",
        successful_repair:"conflict_repaired",
        clarification:"conflict_repaired",
        constructive_follow_up:"conflict_repaired",
        conversation:"supportive_conversation",
        onboarding_support:"supportive_conversation",
        interrupted:"interruption",
        interruption_shared:"interruption",
        ignored_request:"ignored_request",
        milestone_failure_together:"failed_commitment",
        deadline_blame:"failed_commitment",
        dismissive_comment:"dismissive_response",
        credit_dispute:"unfair_credit",
        professional_disagreement:"unresolved_disagreement",
        meeting_conflict:"unresolved_disagreement",
        conflict_observed:"unresolved_disagreement",
        failed_collaboration:"unreliable_collaboration",
        shared_meeting:"routine_meeting",
        same_meeting:"routine_meeting",
        shared_break:"casual_conversation",
        same_break:"casual_conversation",
        casual_conversation:"casual_conversation",
        department_return:"casual_conversation",
        deadline_pressure_together:"mixed_outcome",
        crisis_response_together:"mixed_outcome"
      },
      perRelationshipCap:32,
      perEmployeeCap:96,
      globalCap:720,
      maxSummaries:360,
      maxDebugRecords:160,
      maxSourceEvents:720,
      maxSourceEventAgeDays:730,
      significanceThreshold:1,
      unresolvedPreserveIntensity:3,
      routineDecayDays:14,
      ordinaryDecayDays:75,
      unresolvedDecayDays:220,
      repairedDecayDays:105,
      recallLimit:6,
      emotionalRecallCooldownMinutes:360,
      emotionalRecallMinimumIntensity:2.75,
      emotionalRecallStressMaximum:1.8,
      emotionalRecallMoraleMaximum:1.2
    },
    conversations:{
      schemaVersion:2,
      categories:[
        "greeting","current_work","help_request","giving_help","blockers",
        "meetings","deadlines","appreciation","mentoring","recognition",
        "conflict","repair","casual","company_news","celebration"
      ],
      templatesPerCategory:40,
      maxTemplatesPerCategory:60,
      maxStored:18,
      maxRecentTemplateIds:72,
      maxRecentCategories:16,
      maxRecentPairTemplates:72,
      maxRecentPairTopics:10,
      maxRecentPartnersPerEmployee:10,
      maxKnowledgePerEmployee:24,
      minimumExchanges:4,
      maximumExchanges:5,
      maxVisibleBubbles:4,
      approachDurationMinutes:10,
      minimumLineDurationMinutes:10,
      maximumLineDurationMinutes:25,
      baseLineDurationMinutes:5,
      wordsPerDurationMinute:.65,
      lineDurationStepMinutes:5,
      pauseBetweenExchangesMinutes:5,
      goodbyeDurationMinutes:10,
      resumeDurationMinutes:10,
      movementBaseDurationMs:620,
      movementPerDistanceMs:23,
      movementMaxDurationMs:1800,
      personalSpacePercent:3.2,
      naturalOffsetPercent:.8,
      criticalDeadlineWindowDays:3,
      criticalStressThreshold:84,
      criticalPriorityThreshold:82,
      groundedTriggerTypes:[
        "passing-coworker","meeting-transition","help-request","task-finished",
        "blocker-resolved","milestone","conflict","repair","mentoring",
        "break","department-return","work-coordination","deadline","company-news",
        "first-meeting"
      ],
      explicitRepairTriggerTypes:[
        "apology","apology_accepted","successful_repair","clarification","constructive_follow_up"
      ],
      gestures:["nod","glance","shift-weight","fold-arms","sip-coffee","hand-gesture"],
      humorSafeCategories:["greeting","current_work","casual","appreciation","recognition","celebration"],
      conversationCooldownMinutes:90,
      sourceEventMaxAgeMinutes:180,
      overhearingRange:28,
      overhearingConfidenceScale:.58,
      ordinaryVolume:1,
      privateVolume:.35,
      confidentialVolume:0
    },
    culture:{
      schemaVersion:1,
      dimensions:[
        "collaboration","competitiveness","formality","psychologicalSafety",
        "learningOrientation","recognitionFairness","conflictTolerance",
        "riskTolerance","socialWarmth","accountability","adaptability","inclusiveness"
      ],
      maxEvidence:240,
      dailyMaxDrift:.025,
      recentEvidenceDays:45,
      adaptationRate:.015,
      maxInterpretationModifier:.12,
      minimumEvidenceConfidence:35,
      evidenceStrengthScale:.08
    },
    groups:{
      schemaVersion:1,
      minimumMeaningfulInteractions:2,
      edgeThreshold:44,
      memberJoinThreshold:48,
      maxGroupSize:5,
      maxGroups:24,
      maxHistory:100,
      inactivityDays:45,
      bridgeThreshold:58,
      updateIntervalDays:7,
      initialStability:45,
      persistenceWeight:.72,
      dissolutionStabilityThreshold:18,
      minimumConfidence:8
    },
    leadership:{
      schemaVersion:1,
      maxEvidencePerEmployee:48,
      maxDebugRecords:160,
      emotionalMultiplierMin:.55,
      emotionalMultiplierMax:1.4,
      informalInfluenceThreshold:62,
      updateIntervalDays:7
    },
    workInputForbiddenKeys:[
      "social","relationship","friendship","rivalry","trust","respect",
      "comfort","friction","reputation","affinity","familiarity","cultureAdaptation",
      "informalGroup","leadershipInfluence","socialMemory"
    ]
  },
  cohesion:{
    collaborationBase:45,
    collaborationPerDayWeight:12,
    recentDepartureWindowDays:45,
    layoffPenalty:8,
    departurePenalty:3
  },
  retention:{
    defaultBelonging:50
  },
  recommendations:{
    minScore:5,
    maxScore:95,
    supportScore:66,
    opposeScore:42
  },
  executiveInbox:{
    dailyDecisionMemoLimit:1,
    maxQueuedMemosBeforeRandomEvents:4,
    recentDecisionPressureDays:5,
    recentDecisionPressureLimit:4,
    randomEventChancePerMinute:.004,
    randomEventCooldownMinutes:360,
    decisionCooldownMinutes:720
  },
  rooms:{
    departmentWorkRooms:["software-studio","hardware-lab","executive-suite"],
    capacities:{
      "software-studio":8,
      "hardware-lab":6,
      "meeting-room":8,
      "break-area":6,
      "executive-suite":5
    },
    fallbackCapacity:6,
    maxCongestion:2,
    rerouteThreshold:1.25,
    rerouteMinimumImprovement:.25,
    correctRoomProductivity:1,
    wrongRoomProductivity:.86,
    congestionProductivityPenalty:.18,
    minProductivity:.55,
    maxProductivity:1.12,
    wrongRoomFocusPenalty:.08,
    congestionFocusPenalty:.12,
    maxFocusPenalty:.5,
    congestionStressPenalty:.16,
    breakAreaRecovery:.06,
    minStressEffect:-.12,
    maxStressEffect:.5
  },
  hiring:{
    policyModes:{
      normal:"normal",
      criticalOnly:"critical-only",
      frozen:"frozen"
    },
    requestStartDay:6,
    requestCadenceDays:5,
    requestScoreThreshold:85,
    requestSustainDays:3,
    requestConfidenceThreshold:62,
    duplicateRequestWindowDays:28,
    requestReviewWindowDays:35,
    recentHireDisplayDays:45,
    resolvedRequestCleanupDays:45,
    requestStatuses:{
      queued:"queued",
      approved:"approved-recruiting",
      delayed:"delayed",
      rejected:"rejected",
      suppressed:"suppressed-policy",
      orphaned:"orphaned"
    },
    activeRecruitingStatuses:["requisition","searching","interviewing","offer","exception","paused-policy"],
    advancingRecruitingStatuses:["requisition","searching","interviewing","offer"],
    policyPausableStatuses:["requisition","searching","interviewing","offer","paused-policy"],
    pipelineActiveLimit:48,
    pipelineHistoryLimit:16,
    initialRecruitingCost:.18,
    searchExceptionDays:90,
    searchExceptionAttempts:5,
    contractorCoverageDays:30,
    contractorRepairCoverageDays:14,
    contractorDailyCost:.018,
    missingHireRepairWindowDays:60,
    onboarding:{
      defaultDurationDays:28,
      baseDurationDays:34,
      minDurationDays:18,
      maxDurationDays:36,
      mentorSupportMaxDays:18,
      startingProductivityPercent:20,
      minProductivity:.2,
      socialIntroductionGain:1.2,
      mentorInteractionGain:2.2
    },
    freezeReview:{
      startDay:12,
      cadenceDays:6,
      runwayThresholdDays:62,
      cashThreshold:6,
      minimumSearchAgeDays:4
    },
    scaleUpCashThreshold:24,
    scaleUpValuationThreshold:95,
    scaleUpCustomerThreshold:75,
    scaleUpRevenueThreshold:.08,
    minimumScaleTeam:12
  },
  laborMarket:{
    departments:["hardware","software","quality","product","finance","people","operations","customerSuccess","support"],
    scarcity:{
      hardware:12,
      software:8,
      quality:5,
      product:0,
      finance:-4,
      people:-2,
      operations:2,
      customerSuccess:0,
      support:-6
    },
    baseline:{
      salaryPressure:45,
      averageQuality:55,
      timeToFillDays:18,
      acceptanceRate:68,
      contractorAvailability:55,
      remoteAvailability:58
    }
  },
  employment:{
    benefitsRate:.24,
    payrollTaxRate:.08,
    equipmentAnnual:.018,
    trainingAnnual:.012,
    officeAnnual:.016,
    insuranceAnnual:.009,
    severanceWeeksMin:2,
    severanceWeeksMax:5,
    salarySatisfaction:65
  },
  portfolioDemand:{
    scaleCashThreshold:24,
    scaleValuationThreshold:95,
    scaleCustomerThreshold:75,
    scaleRevenueThreshold:.08,
    maxProjectHeadcount:12,
    maxLegacyProjectHeadcount:8,
    majorProjectDemandBonus:.35,
    launchedDemandBonus:.25,
    qualifiedFteSkillWeight:.55,
    qualifiedFteCapabilityWeight:.45,
    qualifiedFteMax:1.05,
    legacyFlagship:{
      requiredHeadcount:{hardware:2.1,software:1.5,quality:.5,product:.75,finance:.75},
      requiredRoles:["Hardware Engineer","Chip Architect","Industrial Designer","Software Engineer","Firmware Engineer","Software QA Engineer","Product Manager","Finance Analyst"],
      requiredDepartments:["hardware","software","quality","product","finance"]
    }
  },
  leadershipScale:{
    vpValuationThreshold:110,
    vpCustomerThreshold:100,
    vpRevenueThreshold:.18,
    vpEmployeeThreshold:14,
    vpActiveProjectThreshold:3,
    executiveScalePressureMax:30
  },
  organizationGrowth:{
    stageOrder:["startup","growing","scaling","established"],
    maxDepartmentTarget:10,
    learningInfluenceMax:8,
    thresholds:{
      growing:{minimumSignals:2,day:30,cash:20,valuation:60,customers:20,dailyRevenue:.025,activeProjects:2,phases:["integration","customer trial","pilot","launched"]},
      scaling:{minimumSignals:3,day:60,cash:24,valuation:90,customers:60,dailyRevenue:.07,activeProjects:3,phases:["pilot","launched"]},
      established:{minimumSignals:3,day:90,cash:30,valuation:110,customers:100,dailyRevenue:.18,activeProjects:4,phases:["launched"]}
    },
    roleTargets:{
      startup:{
        "Software Engineer":1,"Firmware Engineer":1,"Software QA Engineer":1,"Technical Lead":0,"Software Architect":0,
        "Hardware Engineer":1,"Chip Architect":1,"Electrical Engineer":0,"Industrial Designer":1,"Manufacturing Engineer":0,
        "Product Manager":1,"Finance Analyst":1,"Manager":0,"Director":0,"Vice President":0
      },
      growing:{
        "Software Engineer":2,"Firmware Engineer":2,"Software QA Engineer":2,"Technical Lead":1,"Software Architect":0,
        "Hardware Engineer":2,"Chip Architect":1,"Electrical Engineer":1,"Industrial Designer":1,"Manufacturing Engineer":1,
        "Product Manager":1,"Finance Analyst":1,"Manager":1,"Director":0,"Vice President":0
      },
      scaling:{
        "Software Engineer":3,"Firmware Engineer":2,"Software QA Engineer":2,"Technical Lead":1,"Software Architect":1,
        "Hardware Engineer":3,"Chip Architect":1,"Electrical Engineer":2,"Industrial Designer":1,"Manufacturing Engineer":2,
        "Product Manager":2,"Finance Analyst":2,"Manager":2,"Director":1,"Vice President":0
      },
      established:{
        "Software Engineer":3,"Firmware Engineer":2,"Software QA Engineer":3,"Technical Lead":2,"Software Architect":1,
        "Hardware Engineer":3,"Chip Architect":1,"Electrical Engineer":2,"Industrial Designer":1,"Manufacturing Engineer":2,
        "Product Manager":3,"Finance Analyst":2,"Manager":2,"Director":1,"Vice President":1
      }
    },
    roleSequence:[
      "Manager","Technical Lead","Electrical Engineer","Manufacturing Engineer","Software QA Engineer",
      "Software Engineer","Firmware Engineer","Hardware Engineer","Product Manager","Finance Analyst",
      "Software Architect","Director","Chip Architect","Industrial Designer","Vice President"
    ]
  },
  sound:{
    modes:{
      both:"both",
      alerts:"alerts",
      music:"music",
      off:"off"
    },
    defaultMode:"both"
  },
  aiOwners:{
    work:"work-ai",
    social:"social-ai",
    institutional:"institutional-learning",
    emotional:"emotional-system",
    culture:"culture-system",
    groups:"group-dynamics-system",
    leadership:"leadership-influence-system"
  },
  projectLearning:{
    scoreMin:-10,
    scoreMax:10,
    maxEvidence:5,
    decayDays:720,
    minimumDecay:.35,
    keys:[
      "estimateAccuracy","scopeControl","pilotValue","earlyQA","staffingTiming",
      "cancellationTiming","sunkCostDiscipline","marketTiming","supplierRisk",
      "projectSize","crossDepartmentCoordination","customerValidation","knowledgeValue"
    ]
  },
  workforceLearning:{
    scoreMin:-12,
    scoreMax:12
  },
  institutionalLearning:{
    minimumAttributionQuality:40,
    suppressionIndependenceWindowDays:30,
    reviewWindows:["short","medium","long"],
    reviewRank:{short:1,medium:2,long:3},
    stateRank:{
      unknown:0,
      prior:1,
      hypothesis:1,
      provisional:2,
      validated:3,
      contradicted:0,
      obsolete:0
    },
    stateWeights:{
      validated:1,
      provisional:.20,
      hypothesis:.05,
      prior:.05,
      contradicted:-.10,
      obsolete:0,
      unknown:0
    },
      maxLessons:36,
      maxEpisodes:120,
      maxEvidenceRecords:240,
      maxEvidencePerLesson:6,
    maxEpisodeKeysPerLesson:12,
    maxIndependenceGroupsPerLesson:12
  },
  riskPillars:{
    valuationSnapshotDefault:35,
    weights:{
      financial:.20,
      productDelivery:.20,
      customerMarket:.15,
      workforce:.15,
      operations:.10,
      governance:.10,
      strategic:.10
    },
    labels:{
      financial:"Financial",
      productDelivery:"Product & Delivery",
      customerMarket:"Customer & Market",
      workforce:"Workforce",
      operations:"Operations",
      governance:"Governance",
      strategic:"Strategic"
    }
  },
  manufacturing:{
    fulfillmentThreshold:.62,
    revenuePenaltyRate:.45,
    trustPenaltyScale:2.4,
    customerSentimentPenaltyScale:3,
    customerTrustPenaltyScale:2
  },
  dailyPipeline:{
    version:1,
    captureStageHashesInDebugOnly:true,
    stageOrder:[
      "employee-outcomes",
      "work-items",
      "projects-portfolio",
      "customers-manufacturing",
      "finance",
      "market-labor",
      "valuation",
      "investor-reaction",
      "investor-relations",
      "board",
      "workforce",
      "social-organization",
      "organizational-friction",
      "risk-pillars",
      "crisis-lifecycle",
      "learning-reviews",
      "executive-communication",
      "narrative",
      "telemetry",
      "save"
    ]
  },
  projectStatus:{
    proposal:"proposal",
    planning:"planning",
    approved:"approved",
    prototype:"prototype",
    execution:"execution",
    verification:"verification",
    pilot:"pilot",
    scaling:"scaling",
    atRisk:"at risk",
    blocked:"blocked",
    paused:"paused",
    completed:"completed",
    canceled:"canceled",
    failed:"failed",
    rejected:"rejected",
    merged:"merged"
  },
  projectLifecycle:{
    activeStatuses:["approved","planning","prototype","execution","verification","pilot","scaling","at risk","blocked"],
    activeIncludingPausedStatuses:["approved","planning","prototype","execution","verification","pilot","scaling","at risk","blocked","paused"],
    terminalStatuses:["completed","canceled","failed","rejected","merged"]
  },
  messageStatus:{
    queuedForCeo:"queued-for-ceo",
    active:"active",
    archived:"archived",
    deleted:"deleted"
  },
  hiringStatus:{
    needIdentified:"Need Identified",
    departmentReview:"Department Review",
    financeHrReview:"Finance/HR Review",
    ceoApproval:"CEO Approval",
    candidateSearch:"Candidate Search",
    interviewing:"Interviewing",
    offer:"Offer",
    onboarding:"Onboarding",
    onboardingComplete:"Onboarding Complete",
    paused:"Paused",
    suppressed:"Suppressed"
  },
  startingCompany:{
    cash:18,
    board:72,
    trust:68,
    chip:22,
    software:31,
    quality:38,
    integration:15,
    valuation:42,
    phase:"prototype",
    marketSentiment:50,
    marketConfidence:50,
    leadershipReputation:50,
    valuationQuality:50,
    investorAppetite:50
  }
});
